### ISSUE TITLE
Create dedicated Github action for easy use

### ISSUE THREAD

**Issue by faern** [mullvad/unicop#43]
It would be nice if we created a github action, that makes running `unicop` on any repository a breeze. Something like:

```yml
- name: Scan with unicop
  uses: mullvad/unicop-action@v1
  with:
    log-level: warn
```
